-- Pareto Comparator - Initial Migration
-- Generated by Atlas with manual additions for extensions, functions, triggers, and seed data

-- ============================================
-- Extensions (must be first)
-- ============================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ============================================
-- Tables
-- ============================================

-- Create "categories" table
CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "slug" text NOT NULL, "parent_id" uuid NULL, "description" text NULL, "image_url" text NULL, "attribute_schema" jsonb NULL DEFAULT '{}', "sort_order" integer NULL DEFAULT 0, "active" boolean NULL DEFAULT true, "created_at" timestamptz NULL DEFAULT now(), "updated_at" timestamptz NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "categories_slug_key" UNIQUE ("slug"), CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "idx_categories_active" to table: "categories"
CREATE INDEX "idx_categories_active" ON "categories" ("active") WHERE (active = true);
-- Create index "idx_categories_parent" to table: "categories"
CREATE INDEX "idx_categories_parent" ON "categories" ("parent_id");
-- Create index "idx_categories_slug" to table: "categories"
CREATE INDEX "idx_categories_slug" ON "categories" ("slug");
-- Create "products" table
CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "name" text NOT NULL, "slug" text NOT NULL, "brand" text NOT NULL, "model" text NOT NULL, "ean" text NULL, "sku" text NULL, "image_url" text NULL, "images" jsonb NULL DEFAULT '[]', "attributes" jsonb NULL DEFAULT '{}', "source" text NOT NULL DEFAULT 'brand', "source_url" text NULL, "description" text NULL, "meta_title" text NULL, "meta_description" text NULL, "active" boolean NULL DEFAULT true, "created_at" timestamptz NULL DEFAULT now(), "updated_at" timestamptz NULL DEFAULT now(), "scraped_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "products_ean_key" UNIQUE ("ean"), CONSTRAINT "products_slug_key" UNIQUE ("slug"), CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_products_active" to table: "products"
CREATE INDEX "idx_products_active" ON "products" ("active") WHERE (active = true);
-- Create index "idx_products_attributes" to table: "products"
CREATE INDEX "idx_products_attributes" ON "products" USING gin ("attributes");
-- Create index "idx_products_brand" to table: "products"
CREATE INDEX "idx_products_brand" ON "products" ("brand");
-- Create index "idx_products_category" to table: "products"
CREATE INDEX "idx_products_category" ON "products" ("category_id");
-- Create index "idx_products_ean" to table: "products"
CREATE INDEX "idx_products_ean" ON "products" ("ean") WHERE (ean IS NOT NULL);
-- Create index "idx_products_name_trgm" to table: "products"
CREATE INDEX "idx_products_name_trgm" ON "products" USING gin ("name" gin_trgm_ops);
-- Create index "idx_products_slug" to table: "products"
CREATE INDEX "idx_products_slug" ON "products" ("slug");
-- Create "retailers" table
CREATE TABLE "retailers" ("id" text NOT NULL, "name" text NOT NULL, "slug" text NOT NULL, "website_url" text NOT NULL, "logo_url" text NULL, "affiliate_network" text NULL, "affiliate_id" text NULL, "affiliate_url_template" text NULL, "rate_limit_ms" integer NULL DEFAULT 2000, "anti_bot_level" text NULL DEFAULT 'medium', "active" boolean NULL DEFAULT true, "priority" integer NULL DEFAULT 0, "created_at" timestamptz NULL DEFAULT now(), "updated_at" timestamptz NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "retailers_slug_key" UNIQUE ("slug"));
-- Create index "idx_retailers_active" to table: "retailers"
CREATE INDEX "idx_retailers_active" ON "retailers" ("active") WHERE (active = true);
-- Create index "idx_retailers_priority" to table: "retailers"
CREATE INDEX "idx_retailers_priority" ON "retailers" ("priority" DESC);
-- Create "variants" table
CREATE TABLE "variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "sku" text NOT NULL, "ean" text NULL, "color" text NULL, "color_hex" text NULL, "storage_gb" integer NULL, "ram_gb" integer NULL, "attributes" jsonb NULL DEFAULT '{}', "image_url" text NULL, "msrp" numeric(10,2) NULL, "currency" text NULL DEFAULT 'EUR', "active" boolean NULL DEFAULT true, "created_at" timestamptz NULL DEFAULT now(), "updated_at" timestamptz NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "variants_ean_key" UNIQUE ("ean"), CONSTRAINT "variants_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_variants_color_storage" to table: "variants"
CREATE INDEX "idx_variants_color_storage" ON "variants" ("color", "storage_gb");
-- Create index "idx_variants_ean" to table: "variants"
CREATE INDEX "idx_variants_ean" ON "variants" ("ean") WHERE (ean IS NOT NULL);
-- Create index "idx_variants_product" to table: "variants"
CREATE INDEX "idx_variants_product" ON "variants" ("product_id");
-- Create index "idx_variants_product_sku" to table: "variants"
CREATE UNIQUE INDEX "idx_variants_product_sku" ON "variants" ("product_id", "sku");
-- Create "offers" table
CREATE TABLE "offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "variant_id" uuid NULL, "retailer_id" text NOT NULL, "price" numeric(10,2) NOT NULL, "shipping" numeric(10,2) NULL DEFAULT 0, "currency" text NULL DEFAULT 'EUR', "was_price" numeric(10,2) NULL, "discount_percent" integer NULL, "url" text NOT NULL, "affiliate_url" text NULL, "in_stock" boolean NULL DEFAULT true, "stock_quantity" integer NULL, "delivery_days" integer NULL, "seller_name" text NULL, "is_marketplace" boolean NULL DEFAULT false, "scraped_at" timestamptz NULL DEFAULT now(), "created_at" timestamptz NULL DEFAULT now(), "updated_at" timestamptz NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "offers_product_id_variant_id_retailer_id_key" UNIQUE ("product_id", "variant_id", "retailer_id"), CONSTRAINT "offers_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "offers_retailer_id_fkey" FOREIGN KEY ("retailer_id") REFERENCES "retailers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "offers_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "variants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_offers_in_stock" to table: "offers"
CREATE INDEX "idx_offers_in_stock" ON "offers" ("in_stock") WHERE (in_stock = true);
-- Create index "idx_offers_price" to table: "offers"
CREATE INDEX "idx_offers_price" ON "offers" ("price");
-- Create index "idx_offers_product" to table: "offers"
CREATE INDEX "idx_offers_product" ON "offers" ("product_id");
-- Create index "idx_offers_retailer" to table: "offers"
CREATE INDEX "idx_offers_retailer" ON "offers" ("retailer_id");
-- Create index "idx_offers_scraped_at" to table: "offers"
CREATE INDEX "idx_offers_scraped_at" ON "offers" ("scraped_at" DESC);
-- Create index "idx_offers_variant" to table: "offers"
CREATE INDEX "idx_offers_variant" ON "offers" ("variant_id");
-- Create "affiliate_clicks" table
CREATE TABLE "affiliate_clicks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "offer_id" uuid NOT NULL, "product_id" uuid NOT NULL, "retailer_id" text NOT NULL, "user_agent" text NULL, "ip_hash" text NULL, "referrer" text NULL, "click_id" text NULL, "clicked_at" timestamptz NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "affiliate_clicks_offer_id_fkey" FOREIGN KEY ("offer_id") REFERENCES "offers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "affiliate_clicks_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "affiliate_clicks_retailer_id_fkey" FOREIGN KEY ("retailer_id") REFERENCES "retailers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_affiliate_clicks_date" to table: "affiliate_clicks"
CREATE INDEX "idx_affiliate_clicks_date" ON "affiliate_clicks" ("clicked_at" DESC);
-- Create index "idx_affiliate_clicks_offer" to table: "affiliate_clicks"
CREATE INDEX "idx_affiliate_clicks_offer" ON "affiliate_clicks" ("offer_id");
-- Create index "idx_affiliate_clicks_product" to table: "affiliate_clicks"
CREATE INDEX "idx_affiliate_clicks_product" ON "affiliate_clicks" ("product_id");
-- Create index "idx_affiliate_clicks_retailer" to table: "affiliate_clicks"
CREATE INDEX "idx_affiliate_clicks_retailer" ON "affiliate_clicks" ("retailer_id");
-- Create "price_history" table
CREATE TABLE "price_history" ("time" timestamptz NOT NULL, "product_id" uuid NOT NULL, "variant_id" uuid NULL, "retailer_id" text NOT NULL, "price" numeric(10,2) NOT NULL, "in_stock" boolean NULL DEFAULT true, PRIMARY KEY ("time", "product_id", "retailer_id"), CONSTRAINT "price_history_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "price_history_retailer_id_fkey" FOREIGN KEY ("retailer_id") REFERENCES "retailers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "price_history_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "variants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_price_history_product" to table: "price_history"
CREATE INDEX "idx_price_history_product" ON "price_history" ("product_id", "time" DESC);
-- Create index "idx_price_history_retailer" to table: "price_history"
CREATE INDEX "idx_price_history_retailer" ON "price_history" ("retailer_id", "time" DESC);
-- Create "scrape_jobs" table
CREATE TABLE "scrape_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_type" text NOT NULL, "retailer_id" text NULL, "product_id" uuid NULL, "url" text NULL, "status" text NOT NULL DEFAULT 'pending', "priority" integer NULL DEFAULT 0, "attempts" integer NULL DEFAULT 0, "max_attempts" integer NULL DEFAULT 3, "last_error" text NULL, "scheduled_at" timestamptz NULL DEFAULT now(), "started_at" timestamptz NULL, "completed_at" timestamptz NULL, "next_retry_at" timestamptz NULL, "created_at" timestamptz NULL DEFAULT now(), "updated_at" timestamptz NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "scrape_jobs_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "scrape_jobs_retailer_id_fkey" FOREIGN KEY ("retailer_id") REFERENCES "retailers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "idx_scrape_jobs_next_retry" to table: "scrape_jobs"
CREATE INDEX "idx_scrape_jobs_next_retry" ON "scrape_jobs" ("next_retry_at") WHERE ((status = 'failed'::text) AND (attempts < max_attempts));
-- Create index "idx_scrape_jobs_product" to table: "scrape_jobs"
CREATE INDEX "idx_scrape_jobs_product" ON "scrape_jobs" ("product_id");
-- Create index "idx_scrape_jobs_retailer" to table: "scrape_jobs"
CREATE INDEX "idx_scrape_jobs_retailer" ON "scrape_jobs" ("retailer_id");
-- Create index "idx_scrape_jobs_status" to table: "scrape_jobs"
CREATE INDEX "idx_scrape_jobs_status" ON "scrape_jobs" ("status", "priority" DESC, "scheduled_at");

-- ============================================
-- Functions & Triggers
-- ============================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to all tables with updated_at
CREATE TRIGGER trg_categories_updated_at
    BEFORE UPDATE ON categories
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_retailers_updated_at
    BEFORE UPDATE ON retailers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_variants_updated_at
    BEFORE UPDATE ON variants
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_offers_updated_at
    BEFORE UPDATE ON offers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_scrape_jobs_updated_at
    BEFORE UPDATE ON scrape_jobs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- Seed Data
-- ============================================

-- Default category: Smartphones
INSERT INTO categories (id, name, slug, description, attribute_schema, active)
VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'Smartphones',
    'smartphones',
    'Mobile phones and smartphones',
    '{
        "screen_size": {"type": "number", "unit": "inches"},
        "screen_resolution": {"type": "string"},
        "refresh_rate": {"type": "number", "unit": "Hz"},
        "cpu": {"type": "string"},
        "ram_gb": {"type": "number", "unit": "GB"},
        "storage_gb": {"type": "number", "unit": "GB"},
        "battery_mah": {"type": "number", "unit": "mAh"},
        "fast_charging_w": {"type": "number", "unit": "W"},
        "rear_camera_mp": {"type": "number", "unit": "MP"},
        "front_camera_mp": {"type": "number", "unit": "MP"},
        "5g": {"type": "boolean"},
        "nfc": {"type": "boolean"},
        "water_resistance": {"type": "string"},
        "weight_g": {"type": "number", "unit": "g"}
    }'::jsonb,
    true
) ON CONFLICT (slug) DO NOTHING;

-- Default retailers
INSERT INTO retailers (id, name, slug, website_url, affiliate_network, rate_limit_ms, anti_bot_level, active, priority)
VALUES
    ('amazon_fr', 'Amazon France', 'amazon-fr', 'https://www.amazon.fr', 'amazon', 2000, 'heavy', true, 100),
    ('fnac', 'Fnac', 'fnac', 'https://www.fnac.com', 'awin', 3000, 'heavy', true, 90),
    ('darty', 'Darty', 'darty', 'https://www.darty.com', 'awin', 2000, 'medium', true, 80),
    ('boulanger', 'Boulanger', 'boulanger', 'https://www.boulanger.com', 'awin', 1500, 'light', true, 70),
    ('cdiscount', 'Cdiscount', 'cdiscount', 'https://www.cdiscount.com', 'awin', 3000, 'heavy', true, 60),
    ('ldlc', 'LDLC', 'ldlc', 'https://www.ldlc.com', 'awin', 1500, 'light', true, 50)
ON CONFLICT (id) DO NOTHING;
